[project]
name = "simplex-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "miplib-benchmark>=0.1.2",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
]
